services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AguanteP0stgres!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d
      - ./AdventureWorks2017.bak:/var/opt/mssql/backup/AdventureWorks2017.bak
    networks:
      - db_network
    hostname: sqlserver

  # ============================================================
  # PREVIOUS POSTGRESQL SETUP (COMMENTED OUT)
  # ============================================================
  # postgres:
  #   image: postgres:15
  #   container_name: chinook_postgres
  #   environment:
  #     POSTGRES_DB: chinook
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./init:/docker-entrypoint-initdb.d
  #   networks:
  #     - chinook_network

  # pgadmin:
  #   build:
  #     context: ./pgadmin-config
  #     dockerfile: Dockerfile
  #   container_name: chinook_pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@chinook.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   networks:
  #     - chinook_network
  #   depends_on:
  #     - postgres

volumes:
  sqlserver_data:
  # postgres_data:
  # pgadmin_data:

networks:
  db_network:
    driver: bridge
  # chinook_network:
  #   driver: bridge
